repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.11 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt # v0.1.12 has an issue, where fmt doesn't format the file anymore
      - id: terragrunt-hclfmt
