# https://taskfile.dev

version: '3'

env:
  DOCKER_REGISTRY: '{{default "localhost" .DOCKER_REGISTRY}}'
  DOCKER_IMAGE_NAME: '{{default "terraform-with-terragrunt" .DOCKER_IMAGE_NAME}}'

tasks:
  build-docker-image:
    cmds:
      - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest .
#      - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest

  run-docker-container:
    cmds:
      - docker run --rm -it -v `pwd`:/mnt -w="/mnt" -v ~/.aws/:/home/default/.aws/ -e AWS_PROFILE -e TF_VAR_kubernetes_cluster_ca_certificate -e TF_VAR_datadog_api_key -e TF_VAR_datadog_app_key --user=default --rm $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest

  clean-all:
    cmds:
      - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
      - find . -type d -name ".terraform" -prune -prune -exec rm -rf {} \;
      - find . -type f -name "terraform.tfstate*" -prune -exec rm -rf {} \;
